name: Scan GitHub Actions workflows

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "semgrep-rules/actions/**"
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/**"
      - "semgrep-rules/actions/**"

concurrency:
  group: action-scanning-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read
      security-events: write

    container:
      image: semgrep/semgrep:1.168.0@sha256:525beaba156b9bd3f9847d6ec0eb8f308e11f407e0c0b2da641e7c8dd99c97d6

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Scan workflows
        run: >-
          semgrep scan
          --error
          --sarif
          --output semgrep-results-actions.sarif
          --config semgrep-rules/actions
          .github/workflows

      - name: Save SARIF results
        if: ${{ always() && hashFiles('semgrep-results-actions.sarif') != '' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: semgrep-scan-results-actions
          path: semgrep-results-actions.sarif
          retention-days: 7

      - name: Upload SARIF results
        if: >-
          ${{
            always() &&
            hashFiles('semgrep-results-actions.sarif') != '' &&
            github.actor != 'dependabot[bot]' &&
            (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
          }}
        uses: github/codeql-action/upload-sarif@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4
        with:
          sarif_file: semgrep-results-actions.sarif
          category: semgrep-github-actions
